export const SWITCH_THREAD   = 'SWITCH_THREAD'
export const RECEIVE_ALL     = 'RECEIVE_ALL'
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
export const GET_CHAT_LIST   = 'chatlist.recv'
export const LOG_SUCESS      = 'login.success'
