const CMD_DEFINE	= {
  CMD_CLIENT_LOGIN:0x1001,
    CMD_CLIENT_LOGIN_ACK:0x1002,
    CMD_LOGIN_AUTH:0x1003,
    CMD_LOGIN_AUTH_ACK:0x1004,

    CMD_CLIENT_RECONNECT: 0x1005,

    CMD_CLIENT_RECONNECT_ACK: 0x1006,

    CMD_CLIENT_LOGOUT : 0x1007,

    CMD_CLIENT_LOGOUT_ACK : 0x1008,

    CMD_STATE_REPORT: 0x1009,

    CMD_STATE_REPORT_ACK: 0x100A,


    CMD_HEART_BEAT	:0x9001,
    CMD_HEART_BEAT_ACK	:	0x9002,

    CMD_NETWORK_PING		:	0x9003,

    CMD_NETWORK_PING_ACK	:	0x9004,


    CMD_INVALID_SESSION	:	0x9006,

    CMD_USER_RELOGIN		: 0x9008,

    CMD_FORCE_USER_OUT     :0x900A,


  /*
 * P2P消息
 */
  CMD_P2P_MESSAGE  : 0x4001,
  CMD_RECEIPT_MESSAGE  : 0x4002,

/*
 * 语言交换
 */
  CMD_P2P_LANGUAGEEXCHANGE  : 0x4003,
  CMD_RECEIPT_LANGUAGEEXCHANGE  : 0x4004,

/*
 * 语言交换回复
 */
  CMD_P2P_LANGUAGEEXCHANGE_REPLY  : 0x4005,
  CMD_RECEIPT_LANGUAGEEXCHANGE_REPLY  : 0x4006,


/*
 * 获取未完成语言交换请求
 */
  CMD_GET_UNDONE_LX  : 0x4007,
  CMD_GET_UNDONE_LX_ACK  : 0x4008,

/*
 * 翻译接口改变通知
 */
  CMD_NOTIFY_TRANSLATEAPI_CHANGED  : 0x4009,
  CMD_RECEIPT_TRANSLATEAPI_CHANGED  : 0x400A,

/*
 * P2P系统通知(5条没回复不能收到更多的对方消息)
 */
  CMD_NOTIFY_P2P_SYSTERM  : 0x400B,
  CMD_RECEIPT_P2P_SYSTERM  : 0x400C,



/*
 * 离线消息获取成功确认
 */
  CMD_CONFIRM_OFFLINE_MESSAGE  : 0x4013,
  CMD_CONFIRM_OFFLINE_MESSAGE_ACK  : 0x4014,

/*
 * 消息已读通知
 */
  CMD_P2P_MESSAGESEEN_NOTIFY  : 0x4015,
  CMD_RECEIPT_MESSAGESEEN_NOTIFY  : 0x4016,

/*
 * 对方正在输入通知
 */
  CMD_P2P_INPUTTING_NOTIFY  : 0x4017,

/*
 * 公众号消息
 */
  CMD_P2P_PUBLIC_MESSAGE  : 0x4031,
  CMD_P2P_PUBLIC_MESSAGE_RECEIPT  : 0x4032,

/*
 * 新的获取离线消息协议
 */
  CMD_NEW_GET_OFFLINEMESSAGE  : 0x4041,
  CMD_NEW_GET_OFFLINEMESSAGE_ACK  : 0x4042,


/*
 * 新的获取离线消息协议
 */
  CMD_NEW_GET1_OFFLINEMESSAGE  : 0x4045,
  CMD_NEW_GET1_OFFLINEMESSAGE_ACK  : 0x4046,

  CMD_P2P_VOIP_INVITE  : 0x4019,
  CMD_P2P_VOIP_INVITE_RECEIPT  : 0x401A,
  CMD_P2P_VOIP_INVITE_REJECT  : 0x401B,
  CMD_P2P_VOIP_INVITE_REJECT_RECEIPT  : 0x401C,
  CMD_P2P_VOIP_INVITE_CANCEL  : 0x401D,
  CMD_P2P_VOIP_INVITE_CANCEL_RECEIPT  : 0x401E,
  CMD_P2P_VOIP_INVITE_ACCEPT  : 0x401F,
  CMD_P2P_VOIP_INVITE_ACCEPT_RECEIPT  : 0x4020,
  CMD_P2P_VOIP_CALL_END  : 0x4021,
  CMD_P2P_VOIP_CALL_END_RECEIPT  : 0x4022,

  CMD_VOIP_CONNECTMEDIA_SRV_OK  : 0x4023,
  CMD_VOIP_CONNECTMEDIA_SRV_OK_RECEIPT  : 0x4024,
  CMD_VOIP_SYNCCONNECTMEDIA_SRV_RECEIPT  : 0x4027,
  CMD_VOIP_SYNCCONNECTMEDIA_SRV  : 0x4026,

/*------------------------------------------------------------------------
-- 1V1 Video Chat
-------------------------------------------------------------------------*/
  CMD_P2P_VIDEO_CHAT_INVITE  : 0x4119,
  CMD_P2P_VIDEO_CHAT_INVITE_RECEIPT  : 0x411A,
  CMD_P2P_VIDEO_CHAT_INVITE_REJECT  : 0x411B,
  CMD_P2P_VIDEO_CHAT_INVITE_REJECT_RECEIPT  : 0x411C,
  CMD_P2P_VIDEO_CHAT_INVITE_CANCEL  : 0x411D,
  CMD_P2P_VIDEO_CHAT_INVITE_CANCEL_RECEIPT  : 0x411E,
  CMD_P2P_VIDEO_CHAT_INVITE_ACCEPT  : 0x411F,
  CMD_P2P_VIDEO_CHAT_INVITE_ACCEPT_RECEIPT  : 0x4120,
  CMD_P2P_VIDEO_CHAT_CALL_END  : 0x4121,
  CMD_P2P_VIDEO_CHAT_CALL_END_RECEIPT  : 0x4122,

  CMD_VIDEO_CHAT_CONNECTMEDIA_SRV_OK  : 0x4123,
  CMD_VIDEO_CHAT_CONNECTMEDIA_SRV_OK_RECEIPT  : 0x4124,
  CMD_VIDEO_CHAT_SYNCCONNECTMEDIA_SRV_RECEIPT  : 0x4127,
  CMD_VIDEO_CHAT_SYNCCONNECTMEDIA_SRV  : 0x4126,

  CMD_CLOSE_VIDEO_VIEW  : 0x4129,
  CMD_CLOSE_VIDEO_VIEW_RES  : 0x412A,


/*
 *  webim define
 *
*/
  CMD_GET_RECENT_CHAT_LIST      :	0x9800,
  CMD_GET_RECENT_CHAT_LIST_ACK  :	0x9801,


  CMD_GET_LOGIN_CONFIG      	:	0x9803,
  CMD_GET_LOGIN_CONFIG_ACK  	:	0x9804,

  CMD_SHOW_USER_BASE_INFO      	:	0x9805,
  CMD_SHOW_USER_BASE_INFO_ACK  	:	0x9806,
 }


var MSG_RECEIPT_CODE	=	{
	RCC_SUCCESS : 0,		// 没有捎带信息
	RCC_BLACKUSER : 1,		// 消息发送方是接收方的黑名单用户
	RCC_SPEAKBANNED : 2,	// 消息发送方是系统禁言用户
	RCC_IMAGBANNED : 3,		// 消息发送方是禁止发图用户
	RCC_LANGEX : 4,			// 语言交换的信息
	RCC_UNREGISTERED : 5,	// 消息接收者已经不是注册用户
	RCC_DELETEDUSER : 6,	// 消息接收者因为过多举报和投诉已经删除
	RCC_BANNEDUSER : 7,		// 消息接收用户已经被冻结了 不能回复
	RCC_TSINVITE : 8,		// 用户好友邀请版本戳
	RCC_TSFRIENDINVITE : 9,	// 用户好友邀请版本戳以及好友列表版本戳
	RCC_UNKNOWNERROR : 10,	// 未知错误
	RCC_BANLXMSG : 11,		// 对方不能回复的语言交换消息 4 + 7
	RCC_BANINVITE : 15,		// 对方不能回复的好友邀请 8 + 7
	RCC_IMAGEUNTIL5 : 16,	// 5条消息发图片
	RCC_URLUNTIL5 : 17,		// 5条消息发URL
	RCC_INVITELIMIT : 18,	// 一天最多20个好友请求
	RCC_SENSITIVEINFO : 19,		// 消息中有敏感信息
	RCC_5MOREUTILREPLY : 20,	// 对方无回复最多只能发5条消息
	RCC_5MORECANINVITE : 21,	// 发送5条消息才可以发起voip请求，add by Zengfw
	RCC_LOWVERSION : 22,		// 版本过低，add by Zengfw
	RCC_REJECTBYCALLED : 23,	// 用户免VOIP打扰设置，for ios 1.8.5
    RCC_CONTAINSEXWORD : 24,    // contain sex words
	RCC_MUCMESSAGE_BANNED : 31,	// 被禁言用户不能发群消息
    RCC_ANNIVERSORY_NOTIFY : 32,// anniversory notify type
};

 var CMD_DEFINE_OR 		=	{}
 var MSG_RECEIPT_CODE_OR 	=	{}

var nihao = function(){
 for(var key in CMD_DEFINE){
	  CMD_DEFINE_OR[CMD_DEFINE[key]]= key;
 }

 for(var key in MSG_RECEIPT_CODE){
	  MSG_RECEIPT_CODE_OR[MSG_RECEIPT_CODE[key]]= key;
 }
};
nihao()

 /*
 export const CMD_DEFINE

 export CMD_DEFINE_OR
 export MSG_RECEIPT_CODE_OR
 */
 export   {
    CMD_DEFINE ,
    CMD_DEFINE_OR,
    MSG_RECEIPT_CODE_OR
 }
